In [1]:
import csv
import pandas as pd

In [3]:
business = pd.read_json('../yelp_data/yelp_academic_dataset_business.json', lines=True)

In [4]:
business

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150341,IUQopTMmYQG-qRtBk-8QnA,Binh's Nails,3388 Gateway Blvd,Edmonton,AB,T6J 5H2,53.468419,-113.492054,3.0,13,1,"{'ByAppointmentOnly': 'False', 'RestaurantsPri...","Nail Salons, Beauty & Spas","{'Monday': '10:0-19:30', 'Tuesday': '10:0-19:3..."
150342,c8GjPIOTGVmIemT7j5_SyQ,Wild Birds Unlimited,2813 Bransford Ave,Nashville,TN,37204,36.115118,-86.766925,4.0,5,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Pets, Nurseries & Gardening, Pet Stores, Hobby...","{'Monday': '9:30-17:30', 'Tuesday': '9:30-17:3..."
150343,_QAMST-NrQobXduilWEqSw,Claire's Boutique,"6020 E 82nd St, Ste 46",Indianapolis,IN,46250,39.908707,-86.065088,3.5,8,1,"{'RestaurantsPriceRange2': '1', 'BusinessAccep...","Shopping, Jewelry, Piercing, Toy Stores, Beaut...",None
150344,mtGm22y5c2UHNXDFAjaPNw,Cyclery & Fitness Center,2472 Troy Rd,Edwardsville,IL,62025,38.782351,-89.950558,4.0,24,1,"{'BusinessParking': '{'garage': False, 'street...","Fitness/Exercise Equipment, Eyewear & Optician...","{'Monday': '9:0-20:0', 'Tuesday': '9:0-20:0', ..."
150345,jV_XOycEzSlTx-65W906pg,Sic Ink,238 Apollo Beach Blvd,Apollo beach,FL,33572,27.771002,-82.394910,4.5,9,1,"{'WheelchairAccessible': 'True', 'BusinessAcce...","Beauty & Spas, Permanent Makeup, Piercing, Tattoo","{'Tuesday': '12:0-19:0', 'Wednesday': '12:0-19..."

In [9]:
split_categories = business['categories'].str.split(',', expand = True)
split_categories

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,Doctors,Traditional Chinese Medicine,Naturopathic/Holistic,Acupuncture,Health & Medical,Nutritionists,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,Shipping Centers,Local Services,Notaries,Mailbox Centers,Printing Services,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,Department Stores,Shopping,Fashion,Home & Garden,Electronics,Furniture Stores,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,Restaurants,Food,Bubble Tea,Coffee & Tea,Bakeries,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,Brewpubs,Breweries,Food,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150341,Nail Salons,Beauty & Spas,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
150342,Pets,Nurseries & Gardening,Pet Stores,Hobby Shops,Bird Shops,Home & Garden,Shopping,None,None,None,...,None,None,None,None,None,None,None,None,None,None
150343,Shopping,Jewelry,Piercing,Toy Stores,Beauty & Spas,Accessories,Fashion,None,None,None,...,None,None,None,None,None,None,None,None,None,None
150344,Fitness/Exercise Equipment,Eyewear & Opticians,Shopping,Sporting Goods,Bikes,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
150345,Beauty & Spas,Permanent Makeup,Piercing,Tattoo,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [13]:
ids = business[['business_id']]
ids

                   business_id
0       Pns2l4eNsfO8kk83dixA6A
1       mpf3x-BjTdTEA3yCZrAYPw
2       tUFrWirKiKi_TAnsVWINQQ
3       MTSW4McQd7CbVtyjqoe9mw
4       mWMc6_wTdE0EUBKIGXDVfA
...                        ...
150341  IUQopTMmYQG-qRtBk-8QnA
150342  c8GjPIOTGVmIemT7j5_SyQ
150343  _QAMST-NrQobXduilWEqSw
150344  mtGm22y5c2UHNXDFAjaPNw
150345  jV_XOycEzSlTx-65W906pg

[150346 rows x 1 columns]

In [14]:
stacked = pd.concat([ids, split_categories], axis = 1).set_index('business_id').stack()
stacked

business_id
Pns2l4eNsfO8kk83dixA6A  0                          Doctors
                        1     Traditional Chinese Medicine
                        2            Naturopathic/Holistic
                        3                      Acupuncture
                        4                 Health & Medical
                                         ...
mtGm22y5c2UHNXDFAjaPNw  4                            Bikes
jV_XOycEzSlTx-65W906pg  0                    Beauty & Spas
                        1                 Permanent Makeup
                        2                         Piercing
                        3                           Tattoo
Length: 668592, dtype: object

In [16]:
id_and_category = stacked.reset_index().rename(columns={0: 'category'}).drop('level_1', axis = 1)
id_and_category

                   business_id                       category
0       Pns2l4eNsfO8kk83dixA6A                        Doctors
1       Pns2l4eNsfO8kk83dixA6A   Traditional Chinese Medicine
2       Pns2l4eNsfO8kk83dixA6A          Naturopathic/Holistic
3       Pns2l4eNsfO8kk83dixA6A                    Acupuncture
4       Pns2l4eNsfO8kk83dixA6A               Health & Medical
...                        ...                            ...
668587  mtGm22y5c2UHNXDFAjaPNw                          Bikes
668588  jV_XOycEzSlTx-65W906pg                  Beauty & Spas
668589  jV_XOycEzSlTx-65W906pg               Permanent Makeup
668590  jV_XOycEzSlTx-65W906pg                       Piercing
668591  jV_XOycEzSlTx-65W906pg                         Tattoo

[668592 rows x 2 columns]

In [19]:
id_and_name = business[['business_id', 'name']]
merged = id_and_category.merge(id_and_name, on = 'business_id')
id_name_category = merged[['business_id', 'name', 'category']]
id_name_category

,business_id,name,category
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ",Doctors
1,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ",Traditional Chinese Medicine
2,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ",Naturopathic/Holistic
3,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ",Acupuncture
4,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ",Health & Medical
...,...,...,...
668587,mtGm22y5c2UHNXDFAjaPNw,Cyclery & Fitness Center,Bikes
668588,jV_XOycEzSlTx-65W906pg,Sic Ink,Beauty & Spas
668589,jV_XOycEzSlTx-65W906pg,Sic Ink,Permanent Makeup
668590,jV_XOycEzSlTx-65W906pg,Sic Ink,Piercing
668591,jV_XOycEzSlTx-65W906pg,Sic Ink,Tattoo

In [20]:
# Write to csv
id_name_category.to_csv('../Data/id_name_category.csv', index = False)